---
esphome:
  name: bwt 
  platform: ESP32
  board: mhetesp32minikit

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: BWT-Hotspot
    password: hotspotpw

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

# Enable over-the-air updates
ota:

# Enable Web server
web_server:
  port: 80

i2c:
  sda: 21
  scl: 22
  scan: true
  id: i2cbus

sensor:
  - platform: tcs34725
    red_channel:
      id: red
      name: "Red"
    green_channel:
      id: green
      name: "Green"
    blue_channel:
      id: blue
      name: "Blue"
    clear_channel:
      id: clear
      name: "Clear"
    illuminance:
      id: illuminance
      name: "Illuminance"
    color_temperature:
      id: color_temperature
      name: "Color Temperature"
    gain: 16x
    integration_time: 240ms
    update_interval: 10s

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID
    mac_address:
      name: Mac Wifi Address
    # scan_results:
    #   name: Latest Scan Results

  - platform: version
    name: "ESPHome Version"

  - platform: template
    name: "BWT State"
    lambda: |-
      if (id(blue).state > id(green).state && id(blue).state > id(red).state) {
        return {"Normal"};
      } else if (id(green).state > id(blue).state && id(green).state > id(red).state) {
        return {"Regeneration"};
      } else if (id(red).state > id(blue).state && id(red).state > id(green).state) {
        return {"Error"};
      } else {
        return {"Unknown"};
      }
    update_interval: 5s

